# Generated by Django 3.2.3 on 2021-05-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerid', models.IntegerField()),
                ('offercode', models.CharField(max_length=20)),
                ('offerdescription', models.CharField(max_length=250)),
                ('offerdiscount', models.FloatField()),
            ],
        ),
    ]
